---
output:
  pdf_document: default
  html_document: default
---
```{r}

#initialisation
source("charger.R")
mondata <- charger(2212435)

####Partie a)

#Histogramme
h <-hist(mondata$IR, main = paste("Histogramme de l'indice de rugosité"), col = "lightpink", xlab = " Indice de rugosité (sans unité)", ylab = "Fréquence", xlim = c(0,30), ylim = c(0,50))
text(h$mids,h$counts,labels=h$counts, adj=c(0.5, -0.5))

#tukey
boxplot(mondata$IR,    main=paste("Diagramme de tukey de l'indice de rugosité"),    horizontal=T, xlab = " Indice de rugosité (sans unité)",   col    =    "lightpink")

#droite de Henry
qqnorm(mondata$IR, col= "lightpink", main = paste("Droite de Henry de l'indice de rugosité")) 
qqline(mondata$IR)


#Shapiro
shapiro.test(mondata$IR)


#tableau statistiques descriptives 

conf_int <- t.test(mondata$IR)$conf.int
Interval_Confiance_Min = conf_int[1]
  Interval_Confiance_Max = conf_int[2]
q1 <- quantile(mondata$IR, 0.25)
q2 <- quantile(mondata$IR, 0.5)
q3 <- quantile(mondata$IR, 0.75)
moyenne <- mean(mondata$IR)
ecart_type <- sd(mondata$IR)

dataframe1 <- data.frame(
  moyenne,
  q1,
  q2,
  q3,
  ecart_type,
  Interval_Confiance_Min,
  Interval_Confiance_Max

)

knitr::kable(head(dataframe1),caption="Tableau des statistiques descriptives sur l'indice de rugosité")



```
Explications: 

```{r}
###partie b)
# sous elements pour les types de M
matiere_A <- subset(mondata, M == 0)
matiere_B <- subset(mondata, M == 1)


layout(matrix(c(1, 2), 2, 1, byrow = TRUE), heights = c(1.5, 1))

hist(matiere_A$IR, col = rgb(0, 0, 1, 0.35), freq = FALSE, border = TRUE,
     main = "Histogramme de l'IR selon le type de matériau",
     xlab = "Indice de rugosité", ylab = "Densité")
hist(matiere_B$IR, col = rgb(1, 0, 0, 0.35), freq = FALSE, add = TRUE, border = TRUE)
legend("topright",    inset=0,    title="Type de matériau",
c("Type 0","Type 1"),    fill=c(rgb(0,0,1,0.35),    rgb(1,0,0,0.35)),    cex    =    0.7)
par(mar = c(5, 4, 4, 2) + 0.1)





#####faire le dropbox qui ne fonctionne pas :(

#boxplot(matiere_A$IR,matiere_B$IR,
#horizontal= T, col= c(rgb(0,0,1,0.35),rgb(1,0,0,0.35)),
#main = "Diagramme de Turey de l'IR selon le materiau", xlab="IR")




###### faire le tableau des statistiques descriptives par groupe :((




##### Test d'hypothese



shapiro.test(matiere_A$IR)
shapiro.test(matiere_B$IR)


n1=length(matiere_A$IR)
n2=length(matiere_B$IR)
cat("n_1=",n1,    "\nn_2=",n2)


##### test d'hypothese:
V1=var(matiere_A$IR)
V2=var(matiere_B$IR)
Sp=sqrt(((n1-1)*V1+(n2-1)*V2)/(n1+n2-2))
Z0=(sqrt(V1)-sqrt(V2))/(Sp*sqrt((1/(2*n1))+(1/(2*n2))))
cat("\nZ0=",Z0,"\nZalpha/2=",qnorm(0.05/2,    lower.tail    =    F))


Z1=(mean(matiere_A$IR)-mean(matiere_B$IR))/sqrt((V1/n1)+(V2/n2))
cat("\nZ0=",Z1,"\nZalpha/2=",qnorm(0.05/2, lower.tail = F))

```
